### ISSUE TITLE
Update | Answer #1

### ISSUE THREAD

**Issue by aniland-uz** [jobo-uz/docs#5]
### Discussed in https://github.com/orgs/jobo-uz/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **aniland-uz** July 18, 2022</sup>
Saytda yangilashda qaysi modul va frameworklarni ishlatyabsizlar?</div>

**Comment by theTakhirov** [comment]
https://github.com/jobo-uz/docs/discussions/4#discussioncomment-3171150
